#!/bin/bash
# 2022 - Fernando Della Torre @ BS4IT
# Variaveis
mountpointdefault="/backup"
vg_name_default="vg_backup"
lv_name_default="lv_backup"
source $(dirname "$0")/../functions/colors.sh
source $(dirname "$0")/../functions/get_users.sh
source $(dirname "$0")/../functions/build_banner.sh
if [ -z $serviceuser ]; then
	clear
	build_banner "DISK CONFIGURATION" "bs4it@2022" 41
	echo " "
	echo -e "${YELLOW}ATTENTION!${NC}"
	echo ""
	echo -e "${WHITE}Unable to find service user.${NC}"	
	echo -e "${WHITE}Did you create users a few steps back?${NC}"
	echo ""
	echo -e "${WHITE}Quitting...${NC}"
	read -p "Press ENTER to quit."
	exit 1
fi

clear
build_banner "DISK CONFIGURATION" "bs4it@2022"
echo " "
echo -e "${YELLOW}ATTENTION!${NC}"
echo ""
echo -e "${WHITE}The disk you are going to choose will be completely cleared, used as LVM and formated using XFS.${NC}"
echo -e "${YELLOW}ALL DATA ON THE DISK YOU'LL SELECT WILL BE ${LRED}PERMANENTELY LOST!${NC}"
echo ""
while ! [[ $accept = 'Y' || $accept = 'y' || $accept = 'N' || $accept = 'n' ]]
do
	echo -n -e "Do you really want to go ahead? ${YELLOW}(Y/N)${NC}:"
	read accept
	case $accept in
		y|Y)
			echo ""
			;;
		n|N)
			echo "Quitting, bye!"
			sleep 1
			exit 0
			;;
  	esac
done
clear
build_banner "DISK CONFIGURATION" "bs4it@2022"
echo " "
echo -e "${YELLOW}The following block devices are present:${NC}"
echo " "
lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINT,MODEL
echo " "
echo -e "${YELLOW}NOTE: ${WHITE}You must choose a device with no partition, volume or filesystem.${NC}"
read -p "Press ENTER to continue."
clear
build_banner "DISK CONFIGURATION" "bs4it@2022"
echo " "
echo -e "${YELLOW}The following SCSI devices are attached to this system:${NC}"
echo " "
lsblk -S -o NAME,TYPE,TRAN,VENDOR,MODEL,SIZE
echo " "
while [[ -z "$blkdevice" ]]
do
	echo -n -e "${WHITE}Enter the device you want to use ${NC}(e.g. sdb):${YELLOW} "
	read blkdevice
done
echo -e -n ${NC}
echo ""
echo -e "${LRED}ALL DATA ON $blkdevice WILL BE PERMANENTELY LOST!${NC}"
echo -e "${LRED}THIS PROCESS CANNOT BE UNDONE!${NC}"
echo -e "${LRED}YOU MUST BE SURE ${YELLOW}$blkdevice ${LRED}IS EMPTY OR NO IMPORTANT DATA IS ON IT.${NC}"
echo " "
echo -n -e "${WHITE}Enter the device name again to continue:${YELLOW} "
read confirmdevice
echo -e -n ${NC}
if [ $confirmdevice != $blkdevice ]; then
	echo -e "${YELLOW}The confirmation you entered is wrong, quitting.${NC}"
	echo -e "${YELLOW}Think twice and run this script again.${NC}"
	read -p "Press ENTER to continue."
	exit 1
fi
clear
build_banner "DISK CONFIGURATION" "bs4it@2022" "41"
echo " "
echo -e "${YELLOW}POTENTIAL DATA LOSS WARNING!"
echo " "
echo -e "${WHITE}To cancel this operation press CTRL+C${NC}"
confirmationcode=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1`
echo -n -e "${WHITE}Type this confirmation code to completely erase ${YELLOW}$blkdevice${NC} '$confirmationcode': ${YELLOW}"
read typedconfirmationcode
if [ $typedconfirmationcode != $confirmationcode ]; then
		echo ""
        echo -e "${YELLOW}Wrong code, quitting${NC}"
		read -p "Press ENTER to continue."
        exit 1
fi
echo ""
echo -e "${WHITE}OK.${NC}"
sleep 2
clear
build_banner "DISK CONFIGURATION" "bs4it@2022"
echo " "
sleep 0.3
echo -e "${YELLOW}Operations running."
echo " "
sleep 0.3
echo -n -e "${WHITE}Wiping data from ${YELLOW}$blkdevice${NC}: "
wipefs -aq /dev/$blkdevice
result=$?
sleep 0.3
if [ $result != 0 ]; then
	echo -e "Unable to erase device $blkdevice - error $result"
	echo -e "${YELLOW}This device may be mounted or is part of a LVM. Please verify. Quitting.${NC}"
	read -p "Press ENTER to continue."
	exit 1
fi
echo -e "${LGREEN}OK${NC}"
sleep 0.3
echo -n -e "${WHITE}Creating Physical Volume on ${YELLOW}$blkdevice${WHITE}: ${NC}"
pvcreate /dev/$blkdevice 1> /dev/null
result=$?
sleep 0.3
if [ $result != 0 ]; then
	echo -e "Unable to create Physical Volume - error $result"
	echo -e "This device may be mounted or is part of a LVM. Please verify. Quitting."
	read -p "Press ENTER to continue."
	exit 1
fi
echo -e "${LGREEN}OK${NC}"
sleep 0.3
read -p "Enter the Volume Group Name (vg_backup):" vg_name
	if [ -z $vg_name ]
	then
	        vg_name=$vg_name_default
	fi
echo -n -e "${WHITE}Creating Volume Group ${YELLOW}$vg_name${WHITE}: ${NC}"
vgcreate $vg_name /dev/$blkdevice 1> /dev/null
result=$?
sleep 0.3
if [ $result != 0 ]; then
	echo -e "Unable to create Volume Group - error $result"
	echo -e "Fix what is wrong and try again. Quitting."
	read -p "Press ENTER to continue."
	exit 1
fi
echo -e "${LGREEN}OK${NC}"
sleep 0.3
read -p "Enter the Logical Volume Name (lv_backup):" lv_name
	if [ -z $lv_name ]
	then
	        lv_name=$lv_name_default
	fi
echo -n -e "${WHITE}Creating Logical Volume ${YELLOW}$lv_name${WHITE} using all available space: ${NC}"
lvcreate -l 100%FREE -n $lv_name $vg_name 1> /dev/null
result=$?
sleep 0.3
if [ $result != 0 ]; then
	echo -e "Unable to create Logical Volume - error $result"
	echo -e "Fix what is wrong and try again. Quitting."
	read -p "Press ENTER to continue."
	exit 1
fi
echo -e "${LGREEN}OK${NC}"
sleep 0.3
echo -n -e "${WHITE}Formating with XFS for fast clone support: ${NC}"
mkfs.xfs /dev/$vg_name/$lv_name 1> /dev/null
result=$?
sleep 0.3
if [ $result != 0 ]; then
	echo -e "Unable to create XFS filesystem - error $result"
	echo -e "Fix what is wrong and try again. Quitting."
	read -p "Press ENTER to continue."
	exit 1
fi
echo -e "${LGREEN}OK${NC}"
sleep 0.3
echo -n -e "${WHITE}Checking fstab entry for our filesystem: ${NC}"
fstabmount=$(grep "/dev/mapper/$vg_name-$lv_name" /etc/fstab | grep -v '#' | wc -l)
sleep 0.3
if [ $fstabmount = 0 ]; then
	echo -e ""${YELLOW}Not found. Entry will be created.${NC}""
	sleep 0.2
	read -p "Enter the mountpoint for the new filesystem (e.g. /backup):" mountpoint
	if [ -z $mountpoint ]
	then
	    mountpoint=$mountpointdefault
	fi
	echo -n -e "${WHITE}Creating mount point ${YELLOW}$mountpoint${WHITE}: ${NC}"
	mkdir -p $mountpoint
	sleep 0.3
	echo -e "${LGREEN}OK${NC}"
	sleep 0.6
        echo -n -e "${WHITE}Writting mount mount to /etc/fstab: ${NC}"
	echo "/dev/mapper/$vg_name-$lv_name $mountpoint xfs    defaults,_netdev        0       0" >> /etc/fstab
	sleep 0.3
	echo -e "${LGREEN}OK${NC}"
else
        echo -e "${LGREEN}Mount point already on fstab.${NC}"
		mountpoint=$(grep /dev/mapper/vg_backup-lv_backup /etc/fstab | grep -v '#' | cut -d " " -f 2)
		mkdir -p $mountpoint
fi
sleep 0.3
echo -n -e "${WHITE}Mounting all filesystems in /etc/fstab: ${NC}"
mount -a
result=$?
sleep 0.3
if [ $result != 0 ]; then
	echo ""
    echo -e "Unable to mount some filesystem - error $result"
    echo -e "Verify /etc/fstab"
else
	echo -e "${LGREEN}OK${NC}"
	echo -e "${WHITE}Filesystems mount success.${NC}"
	echo -e "${WHITE}New volume successfully mounted on ${YELLOW}$mountpoint.${NC}"
fi
sleep 0.3
echo -n -e "${WHITE}Setting ${YELLOW}$mountpoint${WHITE} ownership an permissions to service user ${YELLOW}$serviceuser${WHITE}: ${NC}"
chown -R $serviceuser:$serviceuser $mountpoint
chmod -R 700 $mountpoint
echo -e "${LGREEN}OK${NC}"
echo " "
echo -e "Done!"
sleep 1
read -p "Press ENTER to continue."
