#!/bin/bash
# 2022 - Fernando Della Torre @ BS4IT
source $(dirname "$0")/functions/colors.sh
source $(dirname "$0")/functions/IPprefix_by_netmask.sh
source $(dirname "$0")/functions/detect_os.sh
source $(dirname "$0")/functions/build_banner.sh
clear
detect_os
if [ $compatible_kernel == 0 ]; then
	echo -e "However your Kernel \033[1;33m$kernel_major.$kernel_minor\033[0m is not the best for using XFS. At least Kernel \033[1;33m5.4\033[0m is recommended."
	read -p "Press ENTER to continue."
fi
#os="debian-11"
# Quit if not running suported O.S.
# if ! [[ $os == "debian-11" || $os == "ubuntu-20.04" ]]; then
# 	echo -e "${LRED}This script does not support your O.S.${NC}"
# 	echo -e "${LWHITE}You are running ${YELLOW}$os${NC}."
# 	echo ""
# 	exit 0
# fi

clear
build_banner "BS4IT - Linux Hardened Repository Setup Wizard" "bs4it@2022"
echo " "
echo -e "${YELLOW}WELCOME!${NC}" 
#echo "$os detected."
echo " "
echo -e "The next steps will help you to setup a Linux Hardened Repository to store your Veeam Backup & Replication data."
echo ""
while ! [[ $accept = 'Y' || $accept = 'y' || $accept = 'N' || $accept = 'n' ]]
do
	echo -n -e "Do you want to go ahead? ${YELLOW}(Y/N)${NC}:"
	read accept
	case $accept in
		y|Y)
			echo ""
			echo "OK!"
			sleep 0.3
			;;
		n|N)
			echo "Quitting, bye!"
			exit 0
			;;
  	esac
done
clear
build_banner "BS4IT - Linux Hardened Repository Setup Wizard" "bs4it@2022"
echo " "
echo -e "${YELLOW}Step 1 - Network Interface Configuration:${NC}"
echo " "
echo -e "Do you want to setup network interfaces now? "
echo -e "You may lose access to this server depending on your settings."
echo " "
accept=""
while ! [[ $accept = 'Y' || $accept = 'y' || $accept = 'N' || $accept = 'n' ]]
do
	echo -n -e "Start network wizard now? ${YELLOW}(Y/N)${NC}:"
	read accept
	case $accept in
		y|Y)
            bash $(dirname "$0")/modules/bs_set_net
			exitcode=$?
			if [ $exitcode -eq 130 ]; then
				echo $exitcode
				exit 2
			fi
			;;
		n|N)
			;;
  	esac
done

clear
bash $(dirname "$0")/modules/bs_updates+install

clear
build_banner "BS4IT - Linux Hardened Repository Setup Wizard" "bs4it@2022"
echo " "
echo -e "${YELLOW}Step 3 - System Hardening:${NC}"
echo " "
echo -e "You must run this step at least once."
echo " "
read -p "Press ENTER to continue."
bash $(dirname "$0")/modules/bs_harden
sleep 0.6

clear
build_banner "BS4IT - Linux Hardened Repository Setup Wizard" "bs4it@2022"
echo " "
echo -e "${YELLOW}Step 4 - Setup Users:${NC}"
echo " "
echo -e "Do you want to setup users?"
echo -e "If this is the first time you run this wizard this is a mandatory step"
echo " "
accept=""
while ! [[ $accept = 'Y' || $accept = 'y' || $accept = 'N' || $accept = 'n' ]]
do
	echo -n -e "Setup users now? ${YELLOW}(Y/N)${NC}:"
	read accept
	case $accept in
		y|Y)
			echo ""
			sleep 0.3
            bash $(dirname "$0")/modules/bs_set_users
			sleep 0.6
			;;
		n|N)
			;;
  	esac
done

clear
build_banner "BS4IT - Linux Hardened Repository Setup Wizard" "bs4it@2022"
echo " "
echo -e "${YELLOW}Step 5 - Setup iSCSI Initiator:${NC}"
echo " "
echo -e "Do you want to change iSCSI configuration?"
echo -e "If you proceed you may disconnect all active iSCSI sessions."
echo " "
accept=""
while ! [[ $accept = 'Y' || $accept = 'y' || $accept = 'N' || $accept = 'n' ]]
do
	echo -n -e "Start iSCSI initiator wizard now? ${YELLOW}(Y/N)${NC}:"
	read accept
	case $accept in
		y|Y)
			echo ""
			sleep 0.3
            bash $(dirname "$0")/modules/bs_set_iscsi
			;;
		n|N)
			;;
  	esac
done

clear
build_banner "BS4IT - Linux Hardened Repository Setup Wizard" "bs4it@2022"
echo " "
echo -e "${YELLOW}Step 6 - Preparing Disk and Filesystem:${NC}"
echo " "
echo -e "In this step your disk will be prepared on a LVM setup, formated as XFS and mounted accordingly"
echo " "
accept=""
while ! [[ $accept = 'Y' || $accept = 'y' || $accept = 'N' || $accept = 'n' ]]
do
	echo -n -e "Start disk setup wizard now? ${YELLOW}(Y/N)${NC}:"
	read accept
	case $accept in
		y|Y)
			echo ""
			sleep 0.3
            bash $(dirname "$0")/modules/bs_set_disk
			sleep 0.6
			;;
		n|N)
			;;
  	esac
done
clear
build_banner "BS4IT - Linux Hardened Repository Setup Wizard" "bs4it@2022"
echo " "
echo -e "${YELLOW}Step 7 - Add Repository to Veeam B&R Console:${NC}"
echo " "
echo -e "In this step you're going to add this repository to Veeam B&R console."
echo " "
accept=""
while ! [[ $accept = 'Y' || $accept = 'y' || $accept = 'N' || $accept = 'n' ]]
do
	echo -n -e "Do you want to add this repository to VB&R now? ${YELLOW}(Y/N)${NC}:"
	read accept
	case $accept in
		y|Y)
			echo ""
			sleep 0.3
            bash $(dirname "$0")/modules/bs_add_to_console
			echo "The wizard is complete!"
			sleep 0.6
            read -p "Press ENTER to return to main menu."
			;;
		n|N)
			;;
  	esac
done
