#!/bin/bash
# 2022 - Fernando Della Torre @ BS4IT
source $(dirname "$0")/functions/colors.sh
source $(dirname "$0")/functions/IPprefix_by_netmask.sh
source $(dirname "$0")/functions/detect_os.sh
source $(dirname "$0")/functions/build_banner.sh
#version=$(git -C $(dirname "$0") tag -l | tail -1)
version=$(git describe --tags)
trap '' 2
clear
#detect_os
os="debian-11"
compatible_kernel=1
if [ $compatible_kernel == 0 ]; then
	echo -e "However your Kernel \033[1;33m$kernel_major.$kernel_minor\033[0m is not the best for using XFS. At least Kernel \033[1;33m5.4\033[0m is recommended."
	read -p "Press ENTER to continue."
fi
# Quit if not running suported O.S.
# if ! [[ $os == "debian-11" || $os == "ubuntu-20.04" ]]; then
# 	echo -e "${LRED}This script does not support your O.S.${NC}"
# 	echo -e "${LWHITE}You are running ${YELLOW}$os${NC}."
# 	echo ""
# 	exit 0
# fi

while [[ $selection = "" || $selection -le 0  || $selection -gt $count ]]
#while ! [[ $accept = 'Y' || $accept = 'y' || $accept = 'N' || $accept = 'n' ]]
do
	clear
	build_banner "BS4IT - Linux Hardened Repository Setup v$version" "bs4it@2022"
	echo " "
	echo -e "${YELLOW}Linux Hardened Repository Setup${NC}" 
#	echo -e "${CYAN}$os detected.${NC}"
	echo " "
	echo -e "This set of tools helps you to setup and maintain a Linux Hardened Repository."
	echo -e "Select to run the Deploy Wizard or the desired standalone feature."
	echo -e ""
	echo -e " ${YELLOW} 0${NC} - Deploy Wizard"
	echo -e " ${YELLOW} 1${NC} - Set Network Interface"
	echo -e " ${YELLOW} 2${NC} - Update and Install Packages + OS Customizations"
	echo -e " ${YELLOW} 3${NC} - Harden SSH, Firewall + Install Log Collection Script"
	echo -e " ${YELLOW} 4${NC} - Create Users + Get Credentials"
	echo -e " ${YELLOW} 5${NC} - Setup iSCSI"
	echo -e " ${YELLOW} 6${NC} - Setup Disk, LVM, Filesystem and Mount Point + Permissions"
	echo -e " ${YELLOW} 7${NC} - Add to Veeam backup & Replication Console"
	echo -e " ${YELLOW} 8${NC} - Update repository components"
	echo -e " ${YELLOW} 9${NC} - Install Dell OMSA"
	echo -e " ${YELLOW}10${NC} - Check for tool updates"
	echo -e " ${YELLOW}11${NC} - Exit to shell"
	echo -e " ${YELLOW}12${NC} - Logoff"
	echo ""
	echo -n -e "Your selection ${YELLOW}(0-9)${NC}: "
	read selection
	 	if [[ $selection -lt 0  || $selection -gt 12 ]]; then
 			echo "Selection out of range."
			sleep 1
 		fi
	case $selection in
		0)
			(trap 2; bash $(dirname "$0")/bs4it_wizard)
			sleep 0.3
			;;
		1)
			(trap 2; bash $(dirname "$0")/modules/bs_set_net)
			sleep 0.3
			;;
		2)
			(trap 2; bash $(dirname "$0")/modules/bs_updates+install)
			sleep 0.3
			;;
		3)
			(trap 2; bash $(dirname "$0")/modules/bs_harden)
			sleep 0.1
			;;
		4)
			(trap 2; bash $(dirname "$0")/modules/bs_set_users)
			sleep 0.3
			;;
		5)
			(trap 2; bash $(dirname "$0")/modules/bs_set_iscsi)
			sleep 0.3
			;;
		6)
			(trap 2; bash $(dirname "$0")/modules/bs_set_disk)
			sleep 0.3
			;;
		7)
			(bash $(dirname "$0")/modules/bs_add_to_console)
			sleep 0.3
			;;
		8)
			(bash $(dirname "$0")/modules/bs_update_components)
			sleep 0.3
			;;
		9)
			(bash $(dirname "$0")/modules/bs_install_omsa)
			sleep 0.3
			;;
		10)
			echo "To be implemented..."
			#Get latest version
			latest_version=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/bs4it/lnxrepo/releases/latest | rev | cut -d "/" -f1 | rev)
			# check if it is valid
			if [[ $latest_version -eq "latest" ]]; then
				echo "Unable to check por new version."
				sleep 2
				exit
			fi
			echo "depois"
			#git checkout master
			#git pull

			#sleep 1
			sleep 0.3
			;;
		11)
			echo "Entering shell, to return type 'exit'."
			if [ ! -z $(printenv SUDO_USER) ]; then
				runninguser=$(printenv SUDO_USER)
			else
				runninguser=$(printenv USER)
			fi
			trap 2; sudo -u $runninguser /bin/bash
			trap '' 2
			;;
		12)
			echo "Logging off..."
			sleep 1
			exit; logout
			sleep 4
			;;
		
  	esac
done
