#!/bin/bash
# 2022 - Fernando Della Torre @ BS4IT
source $(dirname "$0")/functions/colors.sh
source $(dirname "$0")/functions/IPprefix_by_netmask.sh
source $(dirname "$0")/functions/detect_os.sh
source $(dirname "$0")/functions/build_banner.sh
trap '' 2
clear
#detect_os
os="debian-11"
# Quit if not running suported O.S.
if ! [[ $os == "debian-11" || $os == "ubuntu-20.04" ]]; then
	echo -e "${LRED}This script does not support your O.S.${NC}"
	echo -e "${LWHITE}You are running ${YELLOW}$os${NC}."
	echo ""
	exit 0
fi

# while [[ $nic_selection = "" || $nic_selection -le 0  || $nic_selection -gt $count ]]
# do
# 	echo -n -e "Select NIC by number: "
# 	read nic_selection
# 	if [[ $nic_selection -le 0  || $nic_selection -gt $count ]]; then
# 		echo "Selection out of range."
# 	fi
# done



while [[ $selection = "" || $selection -le 0  || $selection -gt $count ]]
#while ! [[ $accept = 'Y' || $accept = 'y' || $accept = 'N' || $accept = 'n' ]]
do
	clear
	build_banner "BS4IT - Linux Hardened Repository Setup" "bs4it@2022"
	echo " "
	echo -e "${YELLOW}Linux Hardened Repository Setup${NC}" 
#	echo -e "${CYAN}$os detected.${NC}"
	echo " "
	echo -e "This set of tools helps you to setup and maintain a Linux Hardened Repository."
	echo -e "Select to run the Deploy Wizard or the desired standalone feature."
	echo ""
	echo -e ""
	echo -e " ${YELLOW}0${NC} - Deploy Wizard"
	echo -e " ${YELLOW}1${NC} - Set Network Interface"
	echo -e " ${YELLOW}2${NC} - Update and Install Packages + OS Customizations"
	echo -e " ${YELLOW}3${NC} - Harden SSH, Firewall + Install Log Collection Script"
	echo -e " ${YELLOW}4${NC} - Create Users + Get Credentials"
	echo -e " ${YELLOW}5${NC} - Setup iSCSI"
	echo -e " ${YELLOW}6${NC} - Setup Disk, LVM, Filesystem and Mount Point + Permissions"
	echo -e " ${YELLOW}7${NC} - Add to Veeam backup & Replication Console"
	echo -e " ${YELLOW}8${NC} - Update repository components"
	echo -e " ${YELLOW}9${NC} - Exit to shell"
	echo -e " ${YELLOW}10${NC} - Logoff"
	echo ""
	echo -n -e "Your selection ${YELLOW}(0-9)${NC}: "
	read selection
	 	if [[ $selection -lt 0  || $selection -gt 10 ]]; then
 			echo "Selection out of range."
			sleep 1
 		fi
	case $selection in
		0)
			(trap 2; bash $(dirname "$0")/bs4it_wizard)
			sleep 0.3
			;;
		1)
			(trap 2; bash $(dirname "$0")/modules/bs_set_net)
			sleep 0.3
			;;
		2)
			(trap 2; bash $(dirname "$0")/modules/bs_updates+install)
			sleep 0.3
			;;
		3)
			(trap 2; bash $(dirname "$0")/modules/bs_harden)
			sleep 0.3
			;;
		4)
			(trap 2; bash $(dirname "$0")/modules/bs_set_users)
			sleep 0.3
			;;
		5)
			(trap 2; bash $(dirname "$0")/modules/bs_set_iscsi)
			sleep 0.3
			;;
		6)
			(trap 2; bash $(dirname "$0")/modules/bs_set_disk)
			sleep 0.3
			;;
		7)
			(bash $(dirname "$0")/modules/bs_add_to_console)
			sleep 0.3
			;;
		8)
			(bash $(dirname "$0")/modules/bs_update_components)
			sleep 0.3
			;;
		9)
			echo "Entering shell, to return type 'exit'."
			if [ ! -z $(printenv SUDO_USER) ]; then
				runninguser=$(printenv SUDO_USER)
			else
				runninguser=$(printenv USER)
			fi
			sudo -u $runninguser /bin/bash
			;;
		10)
			echo "Logging off..."
			sleep 1
			exit; logout
			sleep 4
			;;
		
  	esac
done
